name: NSE Automation

on:
  schedule:
    - cron: '30 10 * * 1-5'
  workflow_dispatch:

jobs:

  run-script:

    runs-on: ubuntu-latest

    steps:

      # -----------------------------
      # CHECKOUT REPOSITORY
      # -----------------------------

      - name: Checkout Repository
        uses: actions/checkout@v4

      # -----------------------------
      # SETUP PYTHON
      # -----------------------------

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # -----------------------------
      # INSTALL DEPENDENCIES
      # -----------------------------

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      # -----------------------------
      # INSTALL XVFB
      # -----------------------------

      - name: Install XVFB
        run: sudo apt-get install -y xvfb

      # -----------------------------
      # RUN NSE SCRAPER
      # -----------------------------

      - name: Run NSE Scraper
        run: xvfb-run python main.py

      # -----------------------------
      # RUN MASTER DB BUILDER
      # -----------------------------

      - name: Run Master DB Builder
        run: xvfb-run python master_data_builder.py

      # -----------------------------
      # COMMIT AND PUSH FILES
      # -----------------------------

      - name: Commit and Push Files
        run: |

          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add exports/*.xlsx

          git add master_data.xlsx || true

          git add unmatched_symbols.xlsx || true

          git commit -m "Daily NSE automation update" || echo "No changes to commit"

          git push